### ISSUE TITLE
Environment pygem_v2.yml installs python 2.7

### ISSUE THREAD

**Issue by tasinidze** [drounce/PyGEM#31]
Hi,

When I install PyGEM according to https://github.com/drounce/PyGEM/wiki/1.-Getting-Started 
in Ubuntu, I type
$ conda env create -f=pygem_v2.yml
$ conda activate pygem_v2.yml
And then in this environment
$ python --version 
gives me
Python 2.7.15

However, for PyGEM I need Python 3.6.
How can I solve this issue with pygem environment?

**Comment by drounce** [comment]
The new installation instructions should solve this and specify the version requirements.
